### ISSUE TITLE
rabbitmq封装中创建消费者问题

### ISSUE THREAD

**Issue by 2008010688sn** [littlersmall/rabbitmq-access#11]
大神，MQAccessBuilder类中创建consumer使用QueueingConsumer，新版的rabbitmq已不支持这种用法，可以直接使用defaultConsumer创建？有没有其他影响
谢谢

**Comment by littlersmall** [comment]
defaultConsumer 没法做到 QueueingConsumer 的这种逐条消费。所以要升级的话调整很大
