### ISSUE TITLE
QueueingConsumer在新版中已废弃，如何升级到新版本中

### ISSUE THREAD

**Issue by zhang145926** [littlersmall/rabbitmq-access#12]
QueueingConsumer在新版中已废弃，如何升级到新版本中

**Comment by littlersmall** [comment]
主要是新版本没有提供和QueueingConsumer对应的api，他建议的那种模式和我们的设计理念不一样。

**Comment by zhang145926** [comment]
意思是他写的这种模式，新版本的api没有提供？

**Comment by zhang145926** [comment]
那我们可以按照新版本建议的那种模式，重新改造一下么，毕竟新版本中修复了很多已知的BUG啊

**Comment by littlersmall** [comment]
@zhang145926 已升级到最新版本，已去除QueueingConsumer，欢迎体验。

**Comment by zhang145926** [comment]
原来这样子就行了，这几天我看了几天都没改成最新版本，看来我还需要多看看新旧版本的源码，非常感谢
