### ISSUE TITLE
tomcat容器启动的引用不能正常shutdown

### ISSUE THREAD

**Issue by ken209** [littlersmall/rabbitmq-access#13]
你好，执行shutdown.sh不能关闭tomcat， 需要强制kill -9.  有没有好优化建议啊？
日志：
java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.springframework.amqp.rabbit.connection.CachingConnectionFactory]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.

**Comment by littlersmall** [comment]
你需要调用stop命令
具体来说就是你在自己的项目中捕获tomcat关闭事件，然后调用rabbitmq-access的stop命令，安全退出
