### ISSUE TITLE
请问下：进行性能压测的时候，我会出现TIMEOUT WAITING FOR ACK 为啥?

### ISSUE THREAD

**Issue by xfzandysw** [littlersmall/rabbitmq-access#14]
MQAccessBuilder        : send message failed: clean channel shutdown; protocol method: #method<channel.close>(reply-code=406, reply-text=TIMEOUT WAITING FOR ACK, class-id=0, method-id=0)CorrelationData [id=19046]

**Comment by littlersmall** [comment]
超出rabbitmq极限了
