### ISSUE TITLE
【增加topic模式】求教楼主如何直接通过setType("topic")修改为topic模式

### ISSUE THREAD

**Issue by congjianan** [littlersmall/rabbitmq-access#17]
![image](https://user-images.githubusercontent.com/26675869/50734953-f3605000-11e1-11e9-9a2b-c1d2a9dc5b55.png)
像图上这样在PoolExample中添加setType（“topic”）但是一直报如下的错：
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'example' in vhost '/': received 'topic' but current is 'direct', class-id=40, method-id=10)

**Comment by littlersmall** [comment]
这个需要在创建的时候第一次就指定为topic
不能前面是direct创建的，后面改代码想把这个改成topic的。。。

**Comment by congjianan** [comment]
楼主咋改的，能指教下吗？这是我的又一错误示范 ~_~
![image](https://user-images.githubusercontent.com/26675869/50846784-f195b880-13aa-11e9-980a-19482ef6c54b.png)
![image](https://user-images.githubusercontent.com/26675869/50846798-f8bcc680-13aa-11e9-9876-41211d7aa3da.png)
![image](https://user-images.githubusercontent.com/26675869/50846806-fbb7b700-13aa-11e9-843a-891218c67d0f.png)
![image](https://user-images.githubusercontent.com/26675869/50846812-feb2a780-13aa-11e9-85c2-5124dd7460a5.png)
只是启动PoolExample的main方法就报错，
报错信息:
1.


2.
reply-code=406, reply-text=PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'example' in vhost '/': received 'topic' but current is 'direct', class-id=40, method-id=10

**Comment by congjianan** [comment]
Error creating bean with name 'senderExample': Invocation of init method failed; nested exception is java.io.IOException
