### ISSUE TITLE
关于手动确认的疑问

### ISSUE THREAD

**Issue by pleuvoir** [littlersmall/rabbitmq-access#18]
如果业务逻辑落到数据库了，服务宕了，这个时候 ack 还未执行，消费者下线后别的消费者会重新消费此消息，这个问题请问有什么较好的解决方法。

**Comment by zhongx** [comment]
请问SenderExample怎么执行。。。

**Comment by zhongx** [comment]
> 如果业务逻辑落到数据库了，服务宕了，这个时候 ack 还未执行，消费者下线后别的消费者会重新消费此消息，这个问题请问有什么较好的解决方法。

抱歉 请问SenderExample怎么执行。。。

**Comment by littlersmall** [comment]
最好是在消费端实现幂等。
否则就算是没有宕机，在网络有抖动的情况下，消息也可能重复消费的
