### ISSUE TITLE
DetailRes构造方法缺失

### ISSUE THREAD

**Issue by asahouse** [littlersmall/rabbitmq-access#2]
public class DetailRes {
    boolean isSuccess;
    String errMsg;
}

项目中多行使用构造方法均没有在DetailRes中出现
return new DetailRes(false, "");

**Comment by asahouse** [comment]
了解到是使用了 lombok, 但IDEA是会提示缺失编译失败

**Comment by littlersmall** [comment]
请在ide安装lombok插件
