### ISSUE TITLE
项目中的log引用缺失

### ISSUE THREAD

**Issue by asahouse** [littlersmall/rabbitmq-access#3]
例如 MQAccessBuilder中 buildMessageConsumer中, 163行使用了log
但根本没有初始化log.

**Comment by littlersmall** [comment]
log可根据需要引入，推荐使用slf4j，参考依赖如下：
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.1.3</version>
        </dependency>
        <dependency>
            <groupId>org.logback-extensions</groupId>
            <artifactId>logback-ext-spring</artifactId>
            <version>0.1.2</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>jcl-over-slf4j</artifactId>
            <version>1.7.12</version>
        </dependency>
    </dependencies>
另：logback.xml请自行配置
