### ISSUE TITLE
rabbitmq-access 在非spring 环境下怎么使用

### ISSUE THREAD

**Issue by menglinxi** [littlersmall/rabbitmq-access#5]
直接编译成一个jar包后，能在其他项目中使用吗？
<context:component-scan base-package="com.littlersmall.rabbitmqaccess"/>
看到需要配置这个。。。

**Comment by littlersmall** [comment]
@menglinxi  这个项目本身依赖了不少spring框架的代码。如果不在spring项目中使用，需要修改很多地方。
而且component-scan这个实现起来并不容易。
