### ISSUE TITLE
rabbitTemplate.setConfirmCallback  应该是消息成功丢入队列中就会confirm啊？

### ISSUE THREAD

**Issue by yorkexing** [littlersmall/rabbitmq-access#6]
我这边测试的效果是，consumer端打断点，不ack
1. 观察发送端，只要消息进入队列，就会回调rabbitTemplate.setConfirmCallback了
2. 消费端ACK后，rabbitmq核心会删除改消息，但是未触发任何回调。

请问这个是否我设置有问题？

**Comment by littlersmall** [comment]
@yorkexing   这个设置没有任何问题啊。
本来就是两个事情，发送端的ack和消费端的ack是独立的。
发送端发送到队列，就已经可以保证这个消息不回丢失了。
而消费端 成功 消费消息(并得到来自consumer端的确认)，服务端才会删除消息。
