### ISSUE TITLE
请问消费者收到一条消息后就不动了

### ISSUE THREAD

**Issue by ExtremeYu** [littlersmall/rabbitmq-access#8]
![image](https://user-images.githubusercontent.com/16620268/29017337-01b3ee50-7b89-11e7-9913-8f82dfd87125.png)
![image](https://user-images.githubusercontent.com/16620268/29017375-1f3de7fa-7b89-11e7-807f-98b928580aed.png)
![image](https://user-images.githubusercontent.com/16620268/29017389-27414244-7b89-11e7-9825-3aeb850e769f.png)

**Comment by littlersmall** [comment]
rabbitmq默认会多预取一条的，你把consumer端退出，就不会有unacked的消息了

**Comment by ExtremeYu** [comment]
但是一退出，再一起动，还是一个样

**Comment by littlersmall** [comment]
@ExtremeYu  qq 上说。 8322831
